Destroy test environment when test is done and file syncing switched off (fixes #10)
basisjs/yatra pull request #12
Opened 2016-09-26 10:50 UTC by wuzyk

2016-09-26 18:03 UTC, lahmatiy commented on src/runner/test/assert.js
> +          __processAsync();
Why you move it to `try` clause? In that case on `call()` exception async queue will never be processed and test never be done.

2016-09-26 18:06 UTC, lahmatiy commented on src/runner/test/env/iframe.js
> +    if (this.html)
Why not just `this.html = null`? I think `if` is redundant here

2016-09-26 18:45 UTC, lahmatiy commented on src/runner/index.js
> +  doneTestCasesAndSuites.source.setSource(value ? null : testsToRun);
```js
source: new Extract({
    source: fileSync.as(function(value){
      return value ? null : testsToRun;
    }),
    rule: function(test){
      return test.parentNode || test;
    }
  }),
```

2016-09-26 18:48 UTC, lahmatiy commented on src/app/index.js
> +function loadTests(data, autorun, fileSync, notifyLoaderFunction){
I think new argument should be appended, since `notifyLoaderFunction` may using by some one.

2016-09-26 18:49 UTC, lahmatiy requested changes

2016-09-27 05:47 UTC, wuzyk commented on src/runner/index.js
> +  doneTestCasesAndSuites.source.setSource(value ? null : testsToRun);
This will end up with codestyle error, because `doneTestCasesAndSuites` defined but not used.

2016-09-27 06:05 UTC, wuzyk commented on src/runner/test/assert.js
> +          __processAsync();
On exception test gets done in `__exception` call . If call `__processAsync()` after `try/catch` clause `testDone` is called twice.

2016-09-27 10:51 UTC, lahmatiy commented on src/runner/index.js
> +  doneTestCasesAndSuites.source.setSource(value ? null : testsToRun);
Don't use variable then

2016-09-27 12:24 UTC, lahmatiy approved these changes

2016-09-27 12:28 UTC, merged